[package]
name = "minimal-pixels"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Millward <jacob@millward.dev>"]
publish = false

[dependencies]
anyhow = "1.0.79"
ferro-app = { path = "../.." }
